//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egitim()
        {
            this.Kayit = new HashSet<Kayit>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int egitimId { get; set; }
        public string egitimAdi { get; set; }
        public int egitimKatId { get; set; }
        public int egitimiVerenId { get; set; }
        public int egitimUcretliMi { get; set; }
        public string egitimFoto { get; set; }
        public string egitimAciklamasi { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
